/* Generated By:JavaCC: Do not edit this line. SimpleQueryParserConstants.java */
package org.apache.lucene.queryParser;

public interface SimpleQueryParserConstants {

  int EOF = 0;
  int _NUM_CHAR = 1;
  int _ESCAPED_CHAR = 2;
  int _TERM_START_CHAR = 3;
  int _TERM_CHAR = 4;
  int _SKIP_CHAR = 5;
  int AND = 7;
  int OR = 8;
  int NOT = 9;
  int PLUS = 10;
  int MINUS = 11;
  int COLON = 12;
  int BILATERAL_QUOTED = 13;
  int UNILATERAL_QUOTED = 14;
  int QUOTE_AT_THE_END = 15;
  int NUMBER = 16;
  int TERM = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<_NUM_CHAR>",
    "<_ESCAPED_CHAR>",
    "<_TERM_START_CHAR>",
    "<_TERM_CHAR>",
    "<_SKIP_CHAR>",
    "<token of kind 6>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "\"+\"",
    "\"-\"",
    "\":\"",
    "<BILATERAL_QUOTED>",
    "<UNILATERAL_QUOTED>",
    "\"\\\"\"",
    "<NUMBER>",
    "<TERM>",
  };

}
