/* Generated By:JavaCC: Do not edit this line. SimpleQueryParser.java */
package org.apache.lucene.queryParser;

import java.util.Vector;
import java.io.*;
import java.text.*;
import java.util.*;
import org.apache.lucene.index.Term;
import org.apache.lucene.analysis.*;
import org.apache.lucene.document.*;
import org.apache.lucene.search.*;
import org.apache.lucene.util.Parameter;

/**
 * This class is generated by JavaCC.  The most important method is
 * {@link #parse(String)}.
 *
 * The syntax for query strings is as follows:
 * A Query is a series of clauses.
 * A clause may be prefixed by:
 * <ul>
 * <li> a plus (<code>+</code>) or a minus (<code>-</code>) sign, indicating
 * that the clause is required or prohibited respectively; or
 * <li> a term followed by a colon, indicating the field to be searched.
 * This enables one to construct queries which search multiple fields.
 * </ul>
 *
 * A clause may be either:
 * <ul>
 * <li> a term, indicating all the documents that contain this term; or
 * <li> a nested query, enclosed in parentheses.  Note that this may be used
 * with a <code>+</code>/<code>-</code> prefix to require any of a set of
 * terms.
 * </ul>
 *
 * Thus, in BNF, the query grammar is:
 * <pre>
 *   Query  ::= ( Clause )*
 *   Clause ::= ["+", "-"] [&lt;TERM&gt; ":"] ( &lt;TERM&gt; | "(" Query ")" )
 * </pre>
 *
 * <p>
 * Examples of appropriately formatted queries can be found in the <a
 * href="http://lucene.apache.org/java/docs/queryparsersyntax.html">query syntax
 * documentation</a>.
 * </p>
 *
 * <p>In {@link RangeQuery}s, QueryParser tries to detect date values, e.g. <tt>date:[6/1/2005 TO 6/4/2005]</tt>
 * produces a range query that searches for "date" fields between 2005-06-01 and 2005-06-04. Note
 * that the format of the accpeted input depends on {@link #setLocale(Locale) the locale}. This
 * feature also assumes that your index uses the {@link DateField} class to store dates.
 * If you use a different format (e.g. {@link DateTools}) and you still want QueryParser
 * to turn local dates in range queries into valid queries you need to create your own
 * query parser that inherits QueryParser and overwrites
 * {@link #getRangeQuery(String, String, String, boolean)}.</p>
 *
 * <p>Note that QueryParser is <em>not</em> thread-safe.</p>
 *
 * @author Brian Goetz
 * @author Peter Halacsy
 * @author Tatu Saloranta
 */

public class SimpleQueryParser implements SimpleQueryParserConstants {

  private static final int CONJ_NONE   = 0;
  private static final int CONJ_AND    = 1;
  private static final int CONJ_OR     = 2;

  private static final int MOD_NONE    = 0;
  private static final int MOD_NOT     = 10;
  private static final int MOD_REQ     = 11;

  // make it possible to call setDefaultOperator() without accessing 
  // the nested class:
  /** Alternative form of QueryParser.Operator.AND */
  public static final Operator AND_OPERATOR = Operator.AND;
  /** Alternative form of QueryParser.Operator.OR */
  public static final Operator OR_OPERATOR = Operator.OR;

  public static final int FORCE_FIRST_CLAUSE_TO_UNPROHIBITED = 0;
  public static final int APPEND_MATCHALLDOCSQUERY_ONTO_CLAUSES = 1;
  public static final int REMAINS_UNCHANGED = 2;

  /** The actual operator that parser uses to combine query terms */
  private Operator operator = OR_OPERATOR;

  boolean lowercaseExpandedTerms = true;

  Analyzer analyzer;
  String field;
  int phraseSlop = 0;
///   float fuzzyMinSim = FuzzyQuery.defaultMinSimilarity;
///   int fuzzyPrefixLength = FuzzyQuery.defaultPrefixLength;
   Locale locale = Locale.getDefault();

  /** How to process Pure-NOT-Query */
  private int processPureNOTQuery = REMAINS_UNCHANGED;

  /** Valid field names that can be used to build TermQuery */
  HashSet validFieldSet = new HashSet();

  /** The default operator for parsing queries. 
   * Use {@link QueryParser#setDefaultOperator} to change it.
   */
  static public final class Operator extends Parameter {
    private Operator(String name) {
      super(name);
    }
    static public final Operator OR = new Operator("OR");
    static public final Operator AND = new Operator("AND");
  }


  /** Constructs a query parser.
   *  @param f  the default field for query terms.
   *  @param a   used to find terms in the query text.
   */
  public SimpleQueryParser(String f, Analyzer a) {
    this(new FastCharStream(new StringReader("")));
    analyzer = a;
    field = f;

    validFieldSet.add(f);
  }

  /** Parses a query string, returning a {@link org.apache.lucene.search.Query}.
   *  @param query  the query string to be parsed.
   *  @throws ParseException if the parsing fails
   */
  public Query parse(String query) throws ParseException {
    ReInit(new FastCharStream(new StringReader(query)));
    try {
      return Query(field);
    }
    catch (ParseException tme) {
      // rethrow to include the original query:
      throw new ParseException("Cannot parse '" +query+ "': " + tme.getMessage());
    }
    catch (TokenMgrError tme) {
      throw new ParseException("Cannot parse '" +query+ "': " + tme.getMessage());
    }
    catch (BooleanQuery.TooManyClauses tmc) {
      throw new ParseException("Cannot parse '" +query+ "': too many boolean clauses");
    }
  }

   /**
   * @return Returns the analyzer.
   */
  public Analyzer getAnalyzer() {
    return analyzer;
  }

  /**
   * @return Returns the field.
   */
  public String getField() {
    return field;
  }

   /**
   * Get the minimal similarity for fuzzy queries.
   */
///   public float getFuzzyMinSim() {
///       return fuzzyMinSim;
///   }

  /**
   * Set the minimum similarity for fuzzy queries.
   * Default is 0.5f.
   */
///   public void setFuzzyMinSim(float fuzzyMinSim) {
///       this.fuzzyMinSim = fuzzyMinSim;
///   }

   /**
   * Get the prefix length for fuzzy queries. 
   * @return Returns the fuzzyPrefixLength.
   */
///   public int getFuzzyPrefixLength() {
///     return fuzzyPrefixLength;
///   }

  /**
   * Set the prefix length for fuzzy queries. Default is 0.
   * @param fuzzyPrefixLength The fuzzyPrefixLength to set.
   */
///   public void setFuzzyPrefixLength(int fuzzyPrefixLength) {
///     this.fuzzyPrefixLength = fuzzyPrefixLength;
///   }

  /**
   * Sets the default slop for phrases.  If zero, then exact phrase matches
   * are required.  Default value is zero.
   */
  public void setPhraseSlop(int phraseSlop) {
    this.phraseSlop = phraseSlop;
  }

  /**
   * Gets the default slop for phrases.
   */
  public int getPhraseSlop() {
    return phraseSlop;
  }

  /**
   * Sets the boolean operator of the QueryParser.
   * In default mode (<code>OR_OPERATOR</code>) terms without any modifiers
   * are considered optional: for example <code>capital of Hungary</code> is equal to
   * <code>capital OR of OR Hungary</code>.<br/>
   * In <code>AND_OPERATOR</code> mode terms are considered to be in conjuction: the
   * above mentioned query is parsed as <code>capital AND of AND Hungary</code>
   */
  public void setDefaultOperator(Operator op) {
    this.operator = op;
  }


  /**
   * Gets implicit operator setting, which will be either AND_OPERATOR
   * or OR_OPERATOR.
   */
  public Operator getDefaultOperator() {
    return operator;
  }


  /**
   * Whether terms of wildcard, prefix, fuzzy and range queries are to be automatically
   * lower-cased or not.  Default is <code>true</code>.
   */
  public void setLowercaseExpandedTerms(boolean lowercaseExpandedTerms) {
    this.lowercaseExpandedTerms = lowercaseExpandedTerms;
  }


  /**
   * @see #setLowercaseExpandedTerms(boolean)
   */
  public boolean getLowercaseExpandedTerms() {
    return lowercaseExpandedTerms;
  }

  /**
   * Set locale used by date range parsing.
   */
   public void setLocale(Locale locale) {
     this.locale = locale;
   }

  /**
   * Returns current locale, allowing access by subclasses.
   */
   public Locale getLocale() {
     return locale;
   }

  /**
   * Set valid fileds that can be used to build TermQuery
   */
  public void setValidFields(String[] fields) {
    for(int i=0; i<fields.length; i++) {
      validFieldSet.add(fields[i]);
    }
  }

  /**
   * Returns the valid fields.
   */
  public String[] getValidFields() {
    return (String[]) validFieldSet.toArray(new String[0]);
  }

  /**
   *
   */
  public void setProcessPureNOTQuery(int processPureNOTQuery) {
    this.processPureNOTQuery = processPureNOTQuery;
  }

  public int getProcessPureNOTQuery() {
    return this.processPureNOTQuery;
  }

  protected void addClause(Vector clauses, int conj, int mods, Query q) {
    boolean required, prohibited;

    // We might have been passed a null query; the term might have been
    // filtered away by the analyzer.
    if (q == null)
      return;

    // If this term is introduced by AND, make the preceding term required,
    // unless it's already prohibited
    if (clauses.size() > 0 && conj == CONJ_AND) {
      BooleanClause c = (BooleanClause) clauses.elementAt(clauses.size()-1);
      if (!c.isProhibited())
        c.setOccur(BooleanClause.Occur.MUST);
    }

    if (clauses.size() > 0 && operator == AND_OPERATOR && conj == CONJ_OR) {
      // If this term is introduced by OR, make the preceding term optional,
      // unless it's prohibited (that means we leave -a OR b but +a OR b-->a OR b)
      // notice if the input is a OR b, first term is parsed as required; without
      // this modification a OR b would parsed as +a OR b
      BooleanClause c = (BooleanClause) clauses.elementAt(clauses.size()-1);
      if (!c.isProhibited())
        c.setOccur(BooleanClause.Occur.SHOULD);
    }

    // We might have been passed a null query; the term might have been
    // filtered away by the analyzer.
    if (q == null)
      return;

    if (operator == OR_OPERATOR) {
      // We set REQUIRED if we're introduced by AND or +; PROHIBITED if
      // introduced by NOT or -; make sure not to set both.
      prohibited = (mods == MOD_NOT);
      required = (mods == MOD_REQ);
      if (conj == CONJ_AND && !prohibited) {
        required = true;
      }
    } else {
      // We set PROHIBITED if we're introduced by NOT or -; We set REQUIRED
      // if not PROHIBITED and not introduced by OR
      prohibited = (mods == MOD_NOT);
      required   = (!prohibited && conj != CONJ_OR);
    }
    if (required && !prohibited)
      clauses.addElement(new BooleanClause(q, BooleanClause.Occur.MUST));
    else if (!required && !prohibited)
      clauses.addElement(new BooleanClause(q, BooleanClause.Occur.SHOULD));
    else if (!required && prohibited)
      clauses.addElement(new BooleanClause(q, BooleanClause.Occur.MUST_NOT));
    else
      throw new RuntimeException("Clause cannot be both required and prohibited");
  }

  /**
   * @exception ParseException throw in overridden method to disallow
   */
  protected Query getFieldQuery(String field, String queryText)  throws ParseException {
	  return getFieldQuery(field, queryText, false);
  }

  /**
   * @exception ParseException throw in overridden method to disallow
   */
  protected Query getFieldQuery(String field, String queryText, boolean isPhrase)  throws ParseException {
    // Use the analyzer to get all the tokens, and then build a TermQuery,
    // PhraseQuery, or nothing based on the term count

    Vector v = new Vector();
    org.apache.lucene.analysis.Token t;
    int positionCount = 0;
    boolean severalTokensAtSamePosition = false;

    // If the specified field is not a valid one, treat it as a common query text
    if(! validFieldSet.contains(field)) {
      TokenStream source = analyzer.tokenStream(this.field, new StringReader(field));

      while (true) {
        try {
          t = source.next();
        }
        catch (IOException e) {
          t = null;
        }
        if (t == null)
          break;
        if(! t.termText().equals("")) {
          v.addElement(t);
        }
      }
      try {
        source.close();
      }
      catch (IOException e) {
        // ignore
      }
      // reset the invalid field name
      field = this.field;
    }

    TokenStream source = analyzer.tokenStream(field, new StringReader(queryText));

    while (true) {
      try {
        t = source.next();
      }
      catch (IOException e) {
        t = null;
      }
      if (t == null)
        break;
      v.addElement(t);
//System.out.println("SimpleQueryParser.getFieldQuery() - t[" + t + "], t.getPositionIncrement:" + t.getPositionIncrement());
      if (t.getPositionIncrement() != 0)
        positionCount += t.getPositionIncrement();
      else
        severalTokensAtSamePosition = true;
    }
    try {
      source.close();
    }
    catch (IOException e) {
      // ignore
    }

    if (v.size() == 0) {
      return null;
    }
    if (v.size() == 1) {
      t = (org.apache.lucene.analysis.Token) v.elementAt(0);
      return new TermQuery(new Term(field, t.termText()));
    }
    
    // 含同义词的多个Token
    if (severalTokensAtSamePosition) {
      if (positionCount == 1) {
        // no phrase query:
        // 同义词检索 (synonym)
        // 如:"MS" -> {"ms", "microsoft", "微软"}
        BooleanQuery q = new BooleanQuery(true);
        for (int i = 0; i < v.size(); i++) {
          t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//System.out.println("SimpleQueryParser.getFieldQuery() - t[" + i + "][" + t + "]");
//System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + t.termText());
          TermQuery tq = new TermQuery(new Term(field, t.termText()));
          q.add(tq, BooleanClause.Occur.SHOULD);
        }
        return q;
      }
      else {
        if(isPhrase) {
          // phrase query:
          // 含同义词的短语
          // 如:"ms appstore" -> {{"ms", "microsoft", "微软"} appstore} 
          MultiPhraseQuery mpq = new MultiPhraseQuery();
          mpq.setSlop(phraseSlop);
          List multiTerms = new ArrayList();
          for (int i = 0; i < v.size(); i++) {
            t = (org.apache.lucene.analysis.Token) v.elementAt(i);
            if (t.getPositionIncrement() == 1 && multiTerms.size() > 0) {
              mpq.add((Term[])multiTerms.toArray(new Term[0]));
              multiTerms.clear();
            }
            multiTerms.add(new Term(field, t.termText()));
          }
          mpq.add((Term[])multiTerms.toArray(new Term[0]));
          return mpq;
        }
        else {
          //非短语
          BooleanQuery q = new BooleanQuery(true);
          List multiTerms = new ArrayList();
          for (int i = 0; i < v.size(); i++) {
            t = (org.apache.lucene.analysis.Token) v.elementAt(i);
            if (t.getPositionIncrement() == 1 && multiTerms.size() > 0) {
              BooleanQuery sq = new BooleanQuery(true);
              for (int n=0; n<multiTerms.size(); n++) {
                org.apache.lucene.analysis.Token oneToken = 
                 (org.apache.lucene.analysis.Token) multiTerms.get(n);
                TermQuery tq = new TermQuery(
                  new Term(field, oneToken.termText()));
                sq.add(tq, BooleanClause.Occur.SHOULD);
              }
              q.add(sq, BooleanClause.Occur.MUST);
              multiTerms.clear();
            }
            multiTerms.add(new Term(field, t.termText()));
          }
          if (multiTerms.size() > 0) {
          BooleanQuery sq = new BooleanQuery(true);
            for (int n=0; n<multiTerms.size(); n++) {
              org.apache.lucene.analysis.Token oneToken = 
                (org.apache.lucene.analysis.Token) multiTerms.get(n);
              TermQuery tq = new TermQuery(
                new Term(field, oneToken.termText()));
                sq.add(tq, BooleanClause.Occur.SHOULD);
            }
            q.add(sq, BooleanClause.Occur.MUST);
          }
          return q;
        }
      }
    }
    // 不含同义词的多个Token
    else {
//System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery...");
      if(isPhrase) {
        PhraseQuery q = new PhraseQuery();
        q.setSlop(phraseSlop);
        for (int i = 0; i < v.size(); i++) {
          q.add(new Term(field, ((org.apache.lucene.analysis.Token) 
            v.elementAt(i)).termText()));
        }
        return q;
      }
      else {
        BooleanQuery q = new BooleanQuery(true);
        for (int i = 0; i < v.size(); i++) {
          t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//System.out.println("SimpleQueryParser.getFieldQuery() - t[" + i + "][" + t + "]");
//System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + t.termText());
          TermQuery tq = new TermQuery(new Term(field, t.termText()));
          q.add(tq, BooleanClause.Occur.MUST);
        }
        return q;
      }
    }
  }
  
//  /**
//   * @exception ParseException throw in overridden method to disallow
//   */
//  protected Query getFieldQuery(String field, String queryText, boolean isPhrase)  throws ParseException {
//    // Use the analyzer to get all the tokens, and then build a TermQuery,
//    // PhraseQuery, or nothing based on the term count
//
//    Vector v = new Vector();
//    org.apache.lucene.analysis.Token t;
//    int positionCount = 0;
//    boolean severalTokensAtSamePosition = false;
//
//    // If the specified field is not a valid one, treat it as a common query text
//    //changed-------------------------------------------------------------------
//    //if(! validFieldSet.contains(field)) {
//    //changed-------------------------------------------------------------------
//    if(!"".equals(field) && ! validFieldSet.contains(field)) {
//      TokenStream source = analyzer.tokenStream(this.field, new StringReader(field));
//
//      while (true) {
//        try {
//          t = source.next();
//        }
//        catch (IOException e) {
//          t = null;
//        }
//        if (t == null)
//          break;
//        if(! t.termText().equals("")) {
//          v.addElement(t);
//        }
//      }
//      try {
//        source.close();
//      }
//      catch (IOException e) {
//        // ignore
//      }
//      //begin---------------------------------------------------------------
//      // reset the invalid field name
//      //field = this.field;
//      field = "";
//      //end-----------------------------------------------------------------
//    }
//
//    System.out.println("getFieldQuery(" + field + "," + queryText + ")");
//    TokenStream source = analyzer.tokenStream(field, new StringReader(queryText));
//
//    while (true) {
//      try {
//        t = source.next();
//      }
//      catch (IOException e) {
//        t = null;
//      }
//      if (t == null)
//        break;
//      v.addElement(t);
//      System.out.println("t[" + t + "], t.getPositionIncrement:" + t.getPositionIncrement());
//      if (t.getPositionIncrement() != 0)
//        positionCount += t.getPositionIncrement();
//      else
//        severalTokensAtSamePosition = true;
//    }
//    try {
//      source.close();
//    }
//    catch (IOException e) {
//      // ignore
//    }
//
//    if (v.size() == 0) {
//      return null;
//    }
//    if (v.size() == 1) {
//      if (!"".equals(field)) {
//        t = (org.apache.lucene.analysis.Token) v.elementAt(0);
//        return new TermQuery(new Term(field, t.termText()));
//      }
//
//      BooleanQuery q = new BooleanQuery(true);
//      for (int i = 0; i < v.size(); i++) {
//        t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//        TermQuery tq = new TermQuery(new Term(field, t.termText()));
//        q.add(tq, BooleanClause.Occur.SHOULD);
//      }
//      return q;
//    }
//    
//    // 单一字段
//    if (!"".equals(field) || this.fields.length == 1) {
//      if ("".equals(field)) {
//      	field = this.fields[0];
//      }
//System.out.println("severalTokensAtSamePosition:" + severalTokensAtSamePosition);
//System.out.println("positionCount:" + positionCount);
//      // 含同义词的多个Token
//      if (severalTokensAtSamePosition) {
//        if (positionCount == 1) {
//          // no phrase query:
//          // 同义词检索 (synonym)
//          // 如:"MS" -> {"ms", "microsoft", "微软"}
//          BooleanQuery q = new BooleanQuery(true);
//          for (int i = 0; i < v.size(); i++) {
//            t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//System.out.println("t[" + i + "][" + t + "]");
////System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + t.termText());
//            TermQuery tq = new TermQuery(new Term(field, t.termText()));
//            q.add(tq, BooleanClause.Occur.SHOULD);
//          }
//          return q;
//        }
//        else {
//          if(isPhrase) {
//            // phrase query:
//            // 含同义词的短语
//            // 如:"ms appstore" -> {{"ms", "microsoft", "微软"} appstore} 
//            MultiPhraseQuery mpq = new MultiPhraseQuery();
//            mpq.setSlop(phraseSlop);
//            List multiTerms = new ArrayList();
//            for (int i = 0; i < v.size(); i++) {
//              t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//              if (t.getPositionIncrement() == 1 && multiTerms.size() > 0) {
//                mpq.add((Term[])multiTerms.toArray(new Term[0]));
//                multiTerms.clear();
//              }
//              multiTerms.add(new Term(field, t.termText()));
//            }
//            mpq.add((Term[])multiTerms.toArray(new Term[0]));
//            return mpq;
//          }
//          else {
//            //非短语
//            BooleanQuery q = new BooleanQuery(true);
//            List multiTerms = new ArrayList();
//            for (int i = 0; i < v.size(); i++) {
//              t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//              if (t.getPositionIncrement() == 1 && multiTerms.size() > 0) {
//                BooleanQuery sq = new BooleanQuery(true);
//                for (int n=0; n<multiTerms.size(); n++) {
//                  org.apache.lucene.analysis.Token oneToken = 
//                   (org.apache.lucene.analysis.Token) multiTerms.get(n);
//                  TermQuery tq = new TermQuery(
//                    new Term(field, oneToken.termText()));
//                  sq.add(tq, BooleanClause.Occur.SHOULD);
//                }
//                q.add(sq, BooleanClause.Occur.MUST);
//                multiTerms.clear();
//              }
//              multiTerms.add(new Term(field, t.termText()));
//            }
//            if (multiTerms.size() > 0) {
//            BooleanQuery sq = new BooleanQuery(true);
//              for (int n=0; n<multiTerms.size(); n++) {
//                org.apache.lucene.analysis.Token oneToken = 
//                  (org.apache.lucene.analysis.Token) multiTerms.get(n);
//                TermQuery tq = new TermQuery(
//                  new Term(field, oneToken.termText()));
//                  sq.add(tq, BooleanClause.Occur.SHOULD);
//              }
//              q.add(sq, BooleanClause.Occur.MUST);
//            }
//            return q;
//          }
//        }
//      }
//      // 不含同义词的多个Token
//      else {
////System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery...");
//        if(isPhrase) {
//          PhraseQuery q = new PhraseQuery();
//          q.setSlop(phraseSlop);
//          for (int i = 0; i < v.size(); i++) {
//            q.add(new Term(field, ((org.apache.lucene.analysis.Token) 
//              v.elementAt(i)).termText()));
//          }
//          return q;
//        }
//        else {
//          BooleanQuery q = new BooleanQuery(true);
//          for (int i = 0; i < v.size(); i++) {
//            t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//System.out.println("t[" + i + "][" + t + "]");
////System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + t.termText());
//            TermQuery tq = new TermQuery(new Term(field, t.termText()));
//            q.add(tq, BooleanClause.Occur.MUST);
//          }
//          return q;
//        }
//      }
//    }
//    // 多个字段
//    else {
//      // 含同义词的多个Token
//      if (severalTokensAtSamePosition) {
//        if (positionCount == 1) {
//          // no phrase query:
//          // 同义词检索 (synonym)
//          // 如:"MS" -> {"ms", "microsoft", "微软"}
//          BooleanQuery q = new BooleanQuery(true);
//          for (int i = 0; i < v.size(); i++) {
//            t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//System.out.println("t[" + i + "][" + t + "]");
////System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + t.termText());
//            BooleanQuery sq = new BooleanQuery(true);
//            for (int m=0; m<this.fields.length; m++) {
//              TermQuery tq = new TermQuery(
//                new Term(this.fields[m], t.termText()));
//              float boost = this.boosts.get(this.fields[m]) == null ? 1.0f : ((Float) this.boosts.get(this.fields[m])).floatValue();
//              tq.setBoost(boost);
//              sq.add(tq, BooleanClause.Occur.SHOULD);
//            }
//            q.add(sq, BooleanClause.Occur.SHOULD);
//          }
//          return q;
//        }
//        else {
//          if(isPhrase) {
//            // phrase query:
//            // 含同义词的短语
//            // 如:"ms appstore" -> {{"ms", "microsoft", "微软"} appstore} 
//            BooleanQuery q = new BooleanQuery(true);
//            for (int m=0; m<this.fields.length; m++) {
//              MultiPhraseQuery mpq = new MultiPhraseQuery();
//              mpq.setSlop(phraseSlop);
//              List multiTerms = new ArrayList();
//              for (int i = 0; i < v.size(); i++) {
//                t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//                if (t.getPositionIncrement() == 1 && multiTerms.size() > 0) {
//                  mpq.add((Term[])multiTerms.toArray(new Term[0]));
//                  multiTerms.clear();
//                }
//                multiTerms.add(new Term(field, t.termText()));
//              }
//              mpq.add((Term[])multiTerms.toArray(new Term[0]));
//              q.add(mpq, BooleanClause.Occur.SHOULD);
//            }
//            return q;
//          }
//          else {
//            //非短语
//            BooleanQuery q = new BooleanQuery(true);
//            List multiTerms = new ArrayList();
//            for (int i = 0; i < v.size(); i++) {
//              t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//              if (t.getPositionIncrement() == 1 && multiTerms.size() > 0) {
//                BooleanQuery sq = new BooleanQuery(true);
//                for (int m=0; m<this.fields.length; m++) {
//                BooleanQuery ssq = new BooleanQuery(true);
//                  for (int n=0; n<multiTerms.size(); n++) {
//                    org.apache.lucene.analysis.Token oneToken = 
//                     (org.apache.lucene.analysis.Token) multiTerms.get(n);
//                    TermQuery tq = new TermQuery(
//                      new Term(this.fields[m], oneToken.termText()));
//                    float boost = this.boosts.get(this.fields[m]) == null ? 1.0f : ((Float) this.boosts.get(this.fields[m])).floatValue();
//                    tq.setBoost(boost);
//                    ssq.add(tq, BooleanClause.Occur.SHOULD);
//                  }
//                  sq.add(ssq, BooleanClause.Occur.SHOULD);
//                }
//                q.add(sq, BooleanClause.Occur.MUST);
//                multiTerms.clear();
//              }
//              multiTerms.add(new Term(field, t.termText()));
//            }
//            if (multiTerms.size() > 0) {
//              BooleanQuery sq = new BooleanQuery(true);
//              for (int m=0; m<this.fields.length; m++) {
//            	  BooleanQuery ssq = new BooleanQuery(true);
//                for (int n=0; n<multiTerms.size(); n++) {
//                  org.apache.lucene.analysis.Token oneToken = 
//                   (org.apache.lucene.analysis.Token) multiTerms.get(n);
//                  TermQuery tq = new TermQuery(
//                    new Term(this.fields[m], oneToken.termText()));
//                  float boost = this.boosts.get(this.fields[m]) == null ? 1.0f : ((Float) this.boosts.get(this.fields[m])).floatValue();
//                  tq.setBoost(boost);
//                  ssq.add(tq, BooleanClause.Occur.SHOULD);
//                }
//                sq.add(ssq, BooleanClause.Occur.SHOULD);
//              }
//              q.add(sq, BooleanClause.Occur.MUST);
//            }
//            return q;
//          }
//        }
//      }
//      // 不含同义词的多个Token
//      else {
//   	    if(isPhrase) {
//          BooleanQuery q = new BooleanQuery(true);
//          for (int m=0; m<this.fields.length; m++) {
//            PhraseQuery pq = new PhraseQuery();
//            pq.setSlop(phraseSlop);
//            for (int i = 0; i < v.size(); i++) {
//              pq.add(new Term(this.fields[m], ((org.apache.lucene.analysis.Token) 
//                v.elementAt(i)).termText()));
//            }
//            q.add(pq, BooleanClause.Occur.SHOULD);
//          }
//          return q;
//        }
//        else {
//          BooleanQuery q = new BooleanQuery(true);
//          for (int i = 0; i < v.size(); i++) {
//            t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//System.out.println("t[" + i + "][" + t + "]");
////System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + t.termText());
//            BooleanQuery sq = new BooleanQuery(true);
//            for (int m=0; m<this.fields.length; m++) {
//              TermQuery tq = new TermQuery(
//                new Term(this.fields[m], t.termText()));
//              float boost = this.boosts.get(this.fields[m]) == null ? 1.0f : ((Float) this.boosts.get(this.fields[m])).floatValue();
//              tq.setBoost(boost);
//              sq.add(tq, BooleanClause.Occur.SHOULD);
//            }
//            q.add(sq, BooleanClause.Occur.MUST);
//          }
//          return q;
//        }
//      }
//    }
//  }

//  /**
//   * @exception ParseException throw in overridden method to disallow
//   */
//  protected Query getFieldQuery0(String field, String queryText)  throws ParseException {
//    // Use the analyzer to get all the tokens, and then build a TermQuery,
//    // PhraseQuery, or nothing based on the term count
//
//    Vector v = new Vector();
//    org.apache.lucene.analysis.Token t;
//    int positionCount = 0;
//    boolean severalTokensAtSamePosition = false;
//
//    // If the specified field is not a valid one, treat it as a common query text
//    //changed-------------------------------------------------------------------
//    //if(! validFieldSet.contains(field)) {
//    //changed-------------------------------------------------------------------
//    if(!"".equals(field) && ! validFieldSet.contains(field)) {
//      TokenStream source = analyzer.tokenStream(this.field, new StringReader(field));
//
//      while (true) {
//        try {
//          t = source.next();
//        }
//        catch (IOException e) {
//          t = null;
//        }
//        if (t == null)
//          break;
//        if(! t.termText().equals("")) {
//          v.addElement(t);
//        }
//      }
//      try {
//        source.close();
//      }
//      catch (IOException e) {
//        // ignore
//      }
//      //begin---------------------------------------------------------------
//      // reset the invalid field name
//      //field = this.field;
//      field = "";
//      //end-----------------------------------------------------------------
//    }
//
//    System.out.println("getFieldQuery(" + field + "," + queryText + ")");
//    TokenStream source = analyzer.tokenStream(field, new StringReader(queryText));
//
//    while (true) {
//      try {
//        t = source.next();
//      }
//      catch (IOException e) {
//        t = null;
//      }
//      if (t == null)
//        break;
//      v.addElement(t);
//      System.out.println("t[" + t + "], t.getPositionIncrement:" + t.getPositionIncrement());
//      if (t.getPositionIncrement() != 0)
//        positionCount += t.getPositionIncrement();
//      else
//        severalTokensAtSamePosition = true;
//    }
//    try {
//      source.close();
//    }
//    catch (IOException e) {
//      // ignore
//    }
//
//    if (v.size() == 0)
//      return null;
////    else if (v.size() == 1) {
////      t = (org.apache.lucene.analysis.Token) v.elementAt(0);
////      return new TermQuery(new Term(field, t.termText()));
////    } 
//    else {
//System.out.println("severalTokensAtSamePosition:" + severalTokensAtSamePosition);
//System.out.println("positionCount:" + positionCount);
//      if (severalTokensAtSamePosition) {
//        if (positionCount == 1) {
//          // no phrase query:
//          // 同义词检索 (synonym)
//          // 如:"MS" -> {"ms", "microsoft", "微软"}
///**
//          BooleanQuery q = new BooleanQuery(true);
//          for (int i = 0; i < v.size(); i++) {
//            t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//            TermQuery currentQuery = new TermQuery(
//                new Term(field, t.termText()));
//            q.add(currentQuery, BooleanClause.Occur.SHOULD);
//          }
//          return q;
//**/
//          if(!"".equals(field)) { // 指定字段的同义词检索
//            BooleanQuery q = new BooleanQuery(true);
//            for (int i = 0; i < v.size(); i++) {
//              t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//System.out.println("t[" + i + "][" + t + "]");
////System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + t.termText());
//              TermQuery tq = new TermQuery(new Term(field, t.termText()));
//              q.add(tq, BooleanClause.Occur.SHOULD);
//            }
//            return q;
//          }
//          else { // 多字段的同义词检索
//            BooleanQuery q = new BooleanQuery(true);
//            for (int i = 0; i < v.size(); i++) {
//              t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//System.out.println("t[" + i + "][" + t + "]");
////System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + t.termText());
//              BooleanQuery sq = new BooleanQuery(true);
//              for (int m=0; m<this.fields.length; m++) {
//                TermQuery tq = new TermQuery(
//                  new Term(this.fields[m], t.termText()));
//                sq.add(tq, BooleanClause.Occur.SHOULD);
//              }
//              q.add(sq, BooleanClause.Occur.SHOULD);
//            }
//            return q;
//          }
//        }
//        else {
//          if(true) {
///**
//            // phrase query:
//            MultiPhraseQuery mpq = new MultiPhraseQuery();
//            mpq.setSlop(phraseSlop);          
//            List multiTerms = new ArrayList();
//            for (int i = 0; i < v.size(); i++) {
//              t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//              if (t.getPositionIncrement() == 1 && multiTerms.size() > 0) {
//                mpq.add((Term[])multiTerms.toArray(new Term[0]));
//                multiTerms.clear();
//              }
//              multiTerms.add(new Term(field, t.termText()));
//            }
//            mpq.add((Term[])multiTerms.toArray(new Term[0]));
//            return mpq;
//**/
//
//            // phrase query:
//            // 含同义词的短语
//            // 如:"ms appstore" -> {{"ms", "microsoft", "微软"} appstore} 
//            if(!"".equals(field)) { // 指定字段的含同义词的短语
//              MultiPhraseQuery mpq = new MultiPhraseQuery();
//              mpq.setSlop(phraseSlop);
//              List multiTerms = new ArrayList();
//              for (int i = 0; i < v.size(); i++) {
//                t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//                if (t.getPositionIncrement() == 1 && multiTerms.size() > 0) {
//                  mpq.add((Term[])multiTerms.toArray(new Term[0]));
//                  multiTerms.clear();
//                }
//                multiTerms.add(new Term(field, t.termText()));
//              }
//              mpq.add((Term[])multiTerms.toArray(new Term[0]));
//              return mpq;
//            }
//            else { // 多字段的含同义词的短语
//              BooleanQuery q = new BooleanQuery(true);
//              for (int m=0; m<this.fields.length; m++) {
//                MultiPhraseQuery mpq = new MultiPhraseQuery();
//                mpq.setSlop(phraseSlop);
//                List multiTerms = new ArrayList();
//                for (int i = 0; i < v.size(); i++) {
//                  t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//                  if (t.getPositionIncrement() == 1 && multiTerms.size() > 0) {
//                    mpq.add((Term[])multiTerms.toArray(new Term[0]));
//                    multiTerms.clear();
//                  }
//                  multiTerms.add(new Term(field, t.termText()));
//                }
//                mpq.add((Term[])multiTerms.toArray(new Term[0]));
//                q.add(mpq, BooleanClause.Occur.SHOULD);
//              }
//              return q;
//            }
//          }
//          else {
//            //非短语
//            if(!"".equals(field)) { // 指定字段的含同义词的非短语
//              BooleanQuery q = new BooleanQuery(true);
//              List multiTerms = new ArrayList();
//              for (int i = 0; i < v.size(); i++) {
//                t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//                if (t.getPositionIncrement() == 1 && multiTerms.size() > 0) {
//                  BooleanQuery sq = new BooleanQuery(true);
//                  for (int n=0; n<multiTerms.size(); n++) {
//                    org.apache.lucene.analysis.Token oneToken = 
//                     (org.apache.lucene.analysis.Token) multiTerms.get(n);
//                    TermQuery tq = new TermQuery(
//                      new Term(field, oneToken.termText()));
//                    sq.add(tq, BooleanClause.Occur.SHOULD);
//                  }
//                  q.add(sq, BooleanClause.Occur.MUST);
//                  multiTerms.clear();
//                }
//                multiTerms.add(new Term(field, t.termText()));
//              }
//              if (multiTerms.size() > 0) {
//                BooleanQuery sq = new BooleanQuery(true);
//                for (int n=0; n<multiTerms.size(); n++) {
//                  org.apache.lucene.analysis.Token oneToken = 
//                    (org.apache.lucene.analysis.Token) multiTerms.get(n);
//                  TermQuery tq = new TermQuery(
//                    new Term(field, oneToken.termText()));
//                    sq.add(tq, BooleanClause.Occur.SHOULD);
//                }
//                q.add(sq, BooleanClause.Occur.MUST);
//              }
//              return q;
//            }
//            else {
//              BooleanQuery q = new BooleanQuery(true);
//              List multiTerms = new ArrayList();
//              for (int i = 0; i < v.size(); i++) {
//                t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//                if (t.getPositionIncrement() == 1 && multiTerms.size() > 0) {
//                  BooleanQuery sq = new BooleanQuery(true);
//                  for (int m=0; m<this.fields.length; m++) {
//                	BooleanQuery ssq = new BooleanQuery(true);
//                    for (int n=0; n<multiTerms.size(); n++) {
//                      org.apache.lucene.analysis.Token oneToken = 
//                       (org.apache.lucene.analysis.Token) multiTerms.get(n);
//                      TermQuery tq = new TermQuery(
//                        new Term(this.fields[m], oneToken.termText()));
//                      ssq.add(tq, BooleanClause.Occur.SHOULD);
//                    }
//                    sq.add(ssq, BooleanClause.Occur.SHOULD);
//                  }
//                  q.add(sq, BooleanClause.Occur.MUST);
//                  multiTerms.clear();
//                }
//                multiTerms.add(new Term(field, t.termText()));
//              }
//              if (multiTerms.size() > 0) {
//                BooleanQuery sq = new BooleanQuery(true);
//                for (int m=0; m<this.fields.length; m++) {
//              	  BooleanQuery ssq = new BooleanQuery(true);
//                  for (int n=0; n<multiTerms.size(); n++) {
//                    org.apache.lucene.analysis.Token oneToken = 
//                     (org.apache.lucene.analysis.Token) multiTerms.get(n);
//                    TermQuery tq = new TermQuery(
//                      new Term(this.fields[m], oneToken.termText()));
//                    ssq.add(tq, BooleanClause.Occur.SHOULD);
//                  }
//                  sq.add(ssq, BooleanClause.Occur.SHOULD);
//                }
//                q.add(sq, BooleanClause.Occur.MUST);
//              }
//              return q;
//            }
//          }
//        }
//      }
//      else {
///**
//        PhraseQuery q = new PhraseQuery();
//        q.setSlop(phraseSlop);
//        for (int i = 0; i < v.size(); i++) {
//          q.add(new Term(field, ((org.apache.lucene.analysis.Token) 
//              v.elementAt(i)).termText()));
//
//System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + ((org.apache.lucene.analysis.Token) v.elementAt(i)).termText());
//        }
//        
//        return q;
// **/
////begin-------------------------------------------------------------------------
////System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery...");
//        if(true) {
//          if(!"".equals(field)) { // 指定字段的短语
//            PhraseQuery q = new PhraseQuery();
//            q.setSlop(phraseSlop);
//            for (int i = 0; i < v.size(); i++) {
//              q.add(new Term(field, ((org.apache.lucene.analysis.Token) 
//                v.elementAt(i)).termText()));
//
//System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + ((org.apache.lucene.analysis.Token) v.elementAt(i)).termText());
//            }
//            return q;
//          }
//          else {
//            BooleanQuery q = new BooleanQuery(true);
//            for (int m=0; m<this.fields.length; m++) {
//              PhraseQuery pq = new PhraseQuery();
//              pq.setSlop(phraseSlop);
//              for (int i = 0; i < v.size(); i++) {
//                pq.add(new Term(this.fields[m], ((org.apache.lucene.analysis.Token) 
//                  v.elementAt(i)).termText()));
//
//System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + ((org.apache.lucene.analysis.Token) v.elementAt(i)).termText());
//              }
//              q.add(pq, BooleanClause.Occur.SHOULD);
//            }
//            return q;
//          }
//        }
//        else {
//          if(!"".equals(field)) { // 指定字段的多词检索
//            BooleanQuery q = new BooleanQuery(true);
//            for (int i = 0; i < v.size(); i++) {
//              t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//System.out.println("t[" + i + "][" + t + "]");
////System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + t.termText());
//              TermQuery tq = new TermQuery(new Term(field, t.termText()));
//              q.add(tq, BooleanClause.Occur.MUST);
//            }
//            return q;
//          }
//          else { // 多字段的多词检索
//            BooleanQuery q = new BooleanQuery(true);
//            for (int i = 0; i < v.size(); i++) {
//              t = (org.apache.lucene.analysis.Token) v.elementAt(i);
//System.out.println("t[" + i + "][" + t + "]");
////System.out.println("[debug] - SimpleQueryParser.getFieldQuery - prepare PhraseQuery - " + t.termText());
//              BooleanQuery sq = new BooleanQuery(true);
//              for (int m=0; m<this.fields.length; m++) {
//                TermQuery tq = new TermQuery(
//                  new Term(this.fields[m], t.termText()));
//                sq.add(tq, BooleanClause.Occur.SHOULD);
//              }
//              q.add(sq, BooleanClause.Occur.MUST);
//            }
//            return q;
//          }
//        }
////end---------------------------------------------------------------------------
//      }
//    }
//  }


  /**
   * Base implementation delegates to {@link #getFieldQuery(String,String)}.
   * This method may be overridden, for example, to return
   * a SpanNearQuery instead of a PhraseQuery.
   *
   * @exception ParseException throw in overridden method to disallow
   */
  protected Query getFieldQuery(String field, String queryText, int slop)
        throws ParseException {
    ///Query query = getFieldQuery(field, queryText);
    Query query = getFieldQuery(field, queryText, true);

    if (query instanceof PhraseQuery) {
      ((PhraseQuery) query).setSlop(slop);
    }
    if (query instanceof MultiPhraseQuery) {
      ((MultiPhraseQuery) query).setSlop(slop);
    }

    return query;
  }


  /**
   * @exception ParseException throw in overridden method to disallow
   */
///   protected Query getRangeQuery(String field,
///                                 String part1,
///                                 String part2,
///                                 boolean inclusive) throws ParseException
///   {
///     if (lowercaseExpandedTerms) {
///       part1 = part1.toLowerCase();
///       part2 = part2.toLowerCase();
///     }
///     try {
///       DateFormat df = DateFormat.getDateInstance(DateFormat.SHORT, locale);
///       df.setLenient(true);
///       Date d1 = df.parse(part1);
///       Date d2 = df.parse(part2);
///       if (inclusive) {
///         // The user can only specify the date, not the time, so make sure
///         // the time is set to the latest possible time of that date to really
///         // include all documents:
///         Calendar cal = Calendar.getInstance(locale);
///         cal.setTime(d2);
///         cal.set(Calendar.HOUR_OF_DAY, 23);
///         cal.set(Calendar.MINUTE, 59);
///         cal.set(Calendar.SECOND, 59);
///         cal.set(Calendar.MILLISECOND, 999);
///         d2 = cal.getTime();
///       }
///       part1 = DateField.dateToString(d1);
///       part2 = DateField.dateToString(d2);
///     }
///     catch (Exception e) { }
/// 
///     return new RangeQuery(new Term(field, part1),
///                           new Term(field, part2),
///                           inclusive);
///   }

  /**
   * Factory method for generating query, given a set of clauses.
   * By default creates a boolean query composed of clauses passed in.
   *
   * Can be overridden by extending classes, to modify query being
   * returned.
   *
   * @param clauses Vector that contains {@link BooleanClause} instances
   *    to join.
   *
   * @return Resulting {@link Query} object.
   * @exception ParseException throw in overridden method to disallow
   */
  protected Query getBooleanQuery(Vector clauses) throws ParseException {
    return getBooleanQuery(clauses, false);
  }

  /**
   * Factory method for generating query, given a set of clauses.
   * By default creates a boolean query composed of clauses passed in.
   *
   * Can be overridden by extending classes, to modify query being
   * returned.
   *
   * @param clauses Vector that contains {@link BooleanClause} instances
   *    to join.
   * @param disableCoord true if coord scoring should be disabled.
   *
   * @return Resulting {@link Query} object.
   * @exception ParseException throw in overridden method to disallow
   */
  protected Query getBooleanQuery(Vector clauses, boolean disableCoord)
    throws ParseException
  {
    if(clauses.size() == 0) {
      return null;
    }
    if(processPureNOTQuery != REMAINS_UNCHANGED) {
        boolean isPureNOTQuery = true;
        for (int i = 0; i < clauses.size(); i++) {
          BooleanClause clause = (BooleanClause)clauses.elementAt(i);
          if(!clause.isProhibited()) {
            isPureNOTQuery = false;
            break;
          }
        }
        if(isPureNOTQuery) {
          if(processPureNOTQuery == FORCE_FIRST_CLAUSE_TO_UNPROHIBITED) {
            // force the first clause to non-prohibited, if all the boolean 
            // clause are prohibited
            BooleanClause firstClause = (BooleanClause)clauses.elementAt(0);
            firstClause.setOccur(BooleanClause.Occur.SHOULD);
          } else if(processPureNOTQuery == APPEND_MATCHALLDOCSQUERY_ONTO_CLAUSES) {
            // add match-all-docs-query onto the clauses
            clauses.addElement(new BooleanClause(new MatchAllDocsQuery(), BooleanClause.Occur.MUST));
          }
        }
    }

    BooleanQuery query = new BooleanQuery(disableCoord);
    for (int i = 0; i < clauses.size(); i++) {
      query.add((BooleanClause)clauses.elementAt(i));
    }
    return query;
  }

  /**
   * Factory method for generating a query. Called when parser
   * parses an input term token that contains one or more wildcard
   * characters (? and *), but is not a prefix term token (one
   * that has just a single * character at the end)
   *<p>
   * Depending on settings, prefix term may be lower-cased
   * automatically. It will not go through the default Analyzer,
   * however, since normal Analyzers are unlikely to work properly
   * with wildcard templates.
   *<p>
   * Can be overridden by extending classes, to provide custom handling for
   * wildcard queries, which may be necessary due to missing analyzer calls.
   *
   * @param field Name of the field query will use.
   * @param termStr Term token that contains one or more wild card
   *   characters (? or *), but is not simple prefix term
   *
   * @return Resulting {@link Query} built for the term
   * @exception ParseException throw in overridden method to disallow
   */
///   protected Query getWildcardQuery(String field, String termStr) throws ParseException
///   {
///     if (lowercaseExpandedTerms) {
///       termStr = termStr.toLowerCase();
///     }
///     Term t = new Term(field, termStr);
///     return new WildcardQuery(t);
///   }

  /**
   * Factory method for generating a query (similar to
   * {@link #getWildcardQuery}). Called when parser parses an input term
   * token that uses prefix notation; that is, contains a single '*' wildcard
   * character as its last character. Since this is a special case
   * of generic wildcard term, and such a query can be optimized easily,
   * this usually results in a different query object.
   *<p>
   * Depending on settings, a prefix term may be lower-cased
   * automatically. It will not go through the default Analyzer,
   * however, since normal Analyzers are unlikely to work properly
   * with wildcard templates.
   *<p>
   * Can be overridden by extending classes, to provide custom handling for
   * wild card queries, which may be necessary due to missing analyzer calls.
   *
   * @param field Name of the field query will use.
   * @param termStr Term token to use for building term for the query
   *    (<b>without</b> trailing '*' character!)
   *
   * @return Resulting {@link Query} built for the term
   * @exception ParseException throw in overridden method to disallow
   */
///   protected Query getPrefixQuery(String field, String termStr) throws ParseException
///   {
///     if (lowercaseExpandedTerms) {
///       termStr = termStr.toLowerCase();
///     }
///     Term t = new Term(field, termStr);
///     return new PrefixQuery(t);
///   }


   /**
   * Factory method for generating a query (similar to
   * {@link #getWildcardQuery}). Called when parser parses
   * an input term token that has the fuzzy suffix (~) appended.
   *
   * @param field Name of the field query will use.
   * @param termStr Term token to use for building term for the query
   *
   * @return Resulting {@link Query} built for the term
   * @exception ParseException throw in overridden method to disallow
   */
///   protected Query getFuzzyQuery(String field, String termStr, float minSimilarity) throws ParseException
///   {
///     if (lowercaseExpandedTerms) {
///       termStr = termStr.toLowerCase();
///     }
///     Term t = new Term(field, termStr);
///     return new FuzzyQuery(t, minSimilarity, fuzzyPrefixLength);
///   }

  /**
   * Returns a String where the escape char has been
   * removed, or kept only once if there was a double escape.
   */
  private String discardEscapeChar(String input) {
    char[] caSource = input.toCharArray();
    char[] caDest = new char[caSource.length];
    int j = 0;
    for (int i = 0; i < caSource.length; i++) {
      if ((caSource[i] != '\\') || (i > 0 && caSource[i-1] == '\\')) {
        caDest[j++]=caSource[i];
      }
    }
    return new String(caDest, 0, j);
  }

  /**
   * Returns a String where those characters that QueryParser
   * expects to be escaped are escaped by a preceding <code>\</code>.
   */
  public static String escape(String s) {
    StringBuffer sb = new StringBuffer();
    for (int i = 0; i < s.length(); i++) {
      char c = s.charAt(i);
      // NOTE: keep this in sync with _ESCAPED_CHAR below!
      if (c == '\\' || c == '+' || c == '-' || c == '!' || c == '(' || c == ')' || c == ':'
        || c == '^' || c == '[' || c == ']' || c == '\"' || c == '{' || c == '}' || c == '~'
        || c == '*' || c == '?') {
        sb.append('\\');
      }
      sb.append(c);
    }
    return sb.toString();
  }

  /**
   * Command line tool to test QueryParser, using {@link org.apache.lucene.analysis.SimpleAnalyzer}.
   * Usage:<br>
   * <code>java org.apache.lucene.queryParser.QueryParser &lt;input&gt;</code>
   */
  public static void main(String[] args) throws Exception {
    SimpleQueryParser qp = new SimpleQueryParser("field",
                           new org.apache.lucene.analysis.standard.StandardAnalyzer());
    qp.setDefaultOperator(SimpleQueryParser.Operator.AND);
    qp.setValidFields(new String[] {"title", "content", "author"});
    Query q = qp.parse(args[0]);
    System.out.println((q == null) ? "null" : q.toString("field"));
  }

/// <Boost> TOKEN : {
/// <NUMBER:    (<_NUM_CHAR>)+ ( "." (<_NUM_CHAR>)+ )? > : DEFAULT
/// }

/// <RangeIn> TOKEN : {
/// <RANGEIN_TO: "TO">
/// | <RANGEIN_END: "]"> : DEFAULT
/// | <RANGEIN_QUOTED: "\"" (~["\""])+ "\"">
/// | <RANGEIN_GOOP: (~[ " ", "]" ])+ >
/// }

/// <RangeEx> TOKEN : {
/// <RANGEEX_TO: "TO">
/// | <RANGEEX_END: "}"> : DEFAULT
/// | <RANGEEX_QUOTED: "\"" (~["\""])+ "\"">
/// | <RANGEEX_GOOP: (~[ " ", "}" ])+ >
/// }

// *   Query  ::= ( Clause )*
// *   Clause ::= ["+", "-"] [<TERM> ":"] ( <TERM> | "(" Query ")" )
  final public int Conjunction() throws ParseException {
  int ret = CONJ_NONE;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AND:
    case OR:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        jj_consume_token(AND);
            ret = CONJ_AND;
        break;
      case OR:
        jj_consume_token(OR);
              ret = CONJ_OR;
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    {if (true) return ret;}
    throw new Error("Missing return statement in function");
  }

  final public int Modifiers() throws ParseException {
  int ret = MOD_NONE;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
    case PLUS:
    case MINUS:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
              ret = MOD_REQ;
        break;
      case MINUS:
        jj_consume_token(MINUS);
                 ret = MOD_NOT;
        break;
      case NOT:
        jj_consume_token(NOT);
               ret = MOD_NOT;
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    {if (true) return ret;}
    throw new Error("Missing return statement in function");
  }

  final public Query Query(String field) throws ParseException {
  Vector clauses = new Vector();
  Query q, firstQuery=null;
  int conj, mods;
    mods = Modifiers();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 0:
      jj_consume_token(0);
            {if (true) return null;}
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    q = Clause(field);
    addClause(clauses, CONJ_NONE, mods, q);
    if (mods == MOD_NONE) { firstQuery=q; }
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 0:
      case AND:
      case OR:
      case NOT:
      case PLUS:
      case MINUS:
      case COLON:
      case BILATERAL_QUOTED:
      case UNILATERAL_QUOTED:
      case NUMBER:
      case TERM:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_1;
      }
      conj = Conjunction();
      mods = Modifiers();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 0:
        jj_consume_token(0);
        if (clauses.size() == 1 && firstQuery != null) { {if (true) return firstQuery;} }
        else { {if (true) return getBooleanQuery(clauses);} }
        break;
      default:
        jj_la1[6] = jj_gen;
        ;
      }
      q = Clause(field);
      addClause(clauses, conj, mods, q);
    }
    if (clauses.size() == 1 && firstQuery != null) { {if (true) return firstQuery;} }
    else { {if (true) return getBooleanQuery(clauses);} }
    throw new Error("Missing return statement in function");
  }

  final public Query Clause(String field) throws ParseException {
  Query q;
  Token fieldToken=null, boost=null;
    if (jj_2_1(2)) {
      fieldToken = jj_consume_token(TERM);
      jj_consume_token(COLON);
      field=discardEscapeChar(fieldToken.image);
    } else {
      ;
    }
    q = Term(field);
///       if (boost != null) {
///         float f = (float)1.0;
///   try {
///     f = Float.valueOf(boost.image).floatValue();
///           q.setBoost(f);
///   } catch (Exception ignored) { }
///       }
      {if (true) return q;}
    throw new Error("Missing return statement in function");
  }

  final public Query Term(String field) throws ParseException {
  Token term, boost=null, fuzzySlop=null, goop1, goop2;
  boolean prefix = false;
  boolean wildcard = false;
  boolean fuzzy = false;
  boolean rangein = false;
  Query q;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 0:
      jj_consume_token(0);
      {if (true) return getFieldQuery(field, "");}
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMBER:
    case TERM:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TERM:
        term = jj_consume_token(TERM);
        break;
      case NUMBER:
        term = jj_consume_token(NUMBER);
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
       String termImage=discardEscapeChar(term.image);
///        if (wildcard) {
///        q = getWildcardQuery(field, termImage);
///        } else if (prefix) {
///          q = getPrefixQuery(field,
///            discardEscapeChar(term.image.substring
///           (0, term.image.length()-1)));
///        } else if (fuzzy) {
///        	  float fms = fuzzyMinSim;
///        	  try {
///             fms = Float.valueOf(fuzzySlop.image.substring(1)).floatValue();
///        	  } catch (Exception ignored) { }
///        	 if(fms < 0.0f || fms > 1.0f){
///        	   throw new ParseException("Minimum similarity for a FuzzyQuery has to be between 0.0f and 1.0f !");
///        	 }
///        	 q = getFuzzyQuery(field, termImage,fms);
///        } else {
         q = getFieldQuery(field, termImage);
///        }

      break;
    case BILATERAL_QUOTED:
      term = jj_consume_token(BILATERAL_QUOTED);
         int s = phraseSlop;

///          if (fuzzySlop != null) {
///            try {
///              s = Float.valueOf(fuzzySlop.image.substring(1)).intValue();
///            }
///            catch (Exception ignored) { }
///          }
         q = getFieldQuery(field, term.image.substring(1, term.image.length()-1), s);
      break;
    case UNILATERAL_QUOTED:
      term = jj_consume_token(UNILATERAL_QUOTED);
         q = getFieldQuery(field, term.image.substring(1));
      break;
    case AND:
    case OR:
    case NOT:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        term = jj_consume_token(AND);
        break;
      case OR:
        term = jj_consume_token(OR);
        break;
      case NOT:
        term = jj_consume_token(NOT);
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
         q = getFieldQuery(field, term.image);
      break;
    case PLUS:
    case MINUS:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        term = jj_consume_token(PLUS);
        break;
      case MINUS:
        term = jj_consume_token(MINUS);
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
         q = getFieldQuery(field, "");
      break;
    case COLON:
      term = jj_consume_token(COLON);
         q = getFieldQuery(field, "");
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
///     if (boost != null) {
///       float f = (float) 1.0;
///       try {
///         f = Float.valueOf(boost.image).floatValue();
///       }
///       catch (Exception ignored) {
///     /* Should this be handled somehow? (defaults to "no boost", if
///      * boost number is invalid)
///      */
///       }
/// 
///       // avoid boosting null queries, such as those caused by stop words
///       if (q != null) {
///         q.setBoost(f);
///       }
///     }
    {if (true) return q;}
    throw new Error("Missing return statement in function");
  }

  final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_1();
    jj_save(0, xla);
    return retval;
  }

  final private boolean jj_3_1() {
    if (jj_scan_token(TERM)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_scan_token(COLON)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  public SimpleQueryParserTokenManager token_source;
  public Token token, jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  public boolean lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[12];
  final private int[] jj_la1_0 = {0x180,0x180,0xe00,0xe00,0x1,0x37f81,0x1,0x1,0x30000,0x380,0xc00,0x37f80,};
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  public SimpleQueryParser(CharStream stream) {
    token_source = new SimpleQueryParserTokenManager(stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 12; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(CharStream stream) {
    token_source.ReInit(stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 12; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public SimpleQueryParser(SimpleQueryParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 12; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(SimpleQueryParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 12; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    return (jj_scanpos.kind != kind);
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.Vector jj_expentries = new java.util.Vector();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration jenum = jj_expentries.elements(); jenum.hasMoreElements();) {
        int[] oldentry = (int[])(jenum.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  final public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[18];
    for (int i = 0; i < 18; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 12; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 18; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

  final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
    }
    jj_rescan = false;
  }

  final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
